### ISSUE TITLE
Write Project Proposal

### ISSUE THREAD

**Issue by Stefan4D** [Stefan4D/budgetr#13]

**Comment by noeamelya** [comment]
Hi Stefan,

Hope you are doing well! I’m sure that this email content the proposal for presentation but I couldn't see it on my computer, would you please reinvite me again, I’ll try to work on it. Take care!
Thanks

Amelya

From: Stefan ***@***.***>
Date: Tuesday, 26 September 2023 at 20:47
To: Stefan4D/budgetr ***@***.***>
Cc: N Amelya ***@***.***>, Assign ***@***.***>
Subject: [Stefan4D/budgetr] Write Project Proposal (Issue #13)
